### ISSUE TITLE
PengDownloader.py 无法运行

### ISSUE THREAD

**Issue by royluo1984** [00wendi00/Scrapy-Unsplash#1]
大佬您好,
手下感谢您贡献的代码.

FullSite,py版本更新有一些语法过时了, 我改了一下已经可以用了. 
但是下载图片的脚本PengDownloader.py总是报错, 我找不出错在哪里. (我没改动, 因为不知道改哪里)
我用的pycharm python3.7 虚拟环境

![image](https://user-images.githubusercontent.com/26940212/79203565-ccc1a800-7e6d-11ea-8892-11ccaef8de5c.png)

(venv) C:\Users\Administrator\PycharmProjects\UnsplashSpider\UnsplashDownloader>python PengDownloader.py
D:\PythonLab\Unsplash Downloader\Files\photo-1562887284-db69d5836c96?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1586789794680-7be312617841?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1577033906862-94c076ca8e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1586763209828-f0fa0773f19e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1503033978659-0f2764550b47?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1586809624777-cffa5c847a11?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1565500674898-5d9fd92b3893?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1586730113367-5c077569457a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
D:\PythonLab\Unsplash Downloader\Files\photo-1586699160098-49a0a22ab5a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\UnsplashSpider\venv\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "PengDownloader.py", line 21, in downloader
    self.auto_down(url, self.folder + name)  # 下载
  File "PengDownloader.py", line 25, in auto_down
    urllib.request.urlretrieve(url, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
OSError: [Errno 22] Invalid argument: 'D:\\PythonLab\\Unsplash Downloader\\Filesphoto-1586789794680-7be312617841?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg'

**Comment by 00wendi00** [comment]
OSError: [Errno 22] Invalid argument: 'D:\PythonLab\Unsplash Downloader\Filesphoto-1586789794680-7be312617841?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg'

文件名应该是非法的, 简化一下, 不要包括问好啥的

**Comment by 00wendi00** [comment]
OSError: [Errno 22] Invalid argument: 'D:\PythonLab\Unsplash Downloader\Filesphoto-1586789794680-7be312617841?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyNzE1MH0.jpg'

文件名应该是非法的, 简化一下, 不要包括问号啥的

**Comment by hangxiaotian** [comment]
cursor = conn.execute("SELECT LINK FROM LINK WHERE ID <= 30")  # 选择总数
只能下载30张，这里我修改为大于30的数字不行。

**Comment by 00wendi00** [comment]
> cursor = conn.execute("SELECT LINK FROM LINK WHERE ID <= 30") # 选择总数
> 只能下载30张，这里我修改为大于30的数字不行。

是啊.  这个已经很久了 😆
